### ISSUE TITLE
Usar valueOf

### ISSUE THREAD

**Issue by matheusgr** [alessandroliafook/contrato#10]
Pode usar o FuncaoPessoa.valueOf(String) para recuperar o enum equivalente.

https://github.com/alessandroliafook/contrato/blob/4049cb32b4298b56eb58e1dfe6cf4f85ed74deeb/src/main/java/alessandrofook/contrato/model/pessoa/FuncaoPessoa.java#L19

**Comment by alessandroliafook** [comment]
Resolvido com o commit f48ea2fb33a190957ffc17eb2c3330434be8e3d7
