### ISSUE TITLE
Hashcode e Equals estão diferentes

### ISSUE THREAD

**Issue by matheusgr** [alessandroliafook/contrato#11]
Uniformizar a semântica do hc e eq.

https://github.com/alessandroliafook/contrato/blob/4049cb32b4298b56eb58e1dfe6cf4f85ed74deeb/src/main/java/alessandrofook/contrato/model/pessoa/Pessoa.java#L87

**Comment by alessandroliafook** [comment]
Resolvido com o commit f48ea2fb33a190957ffc17eb2c3330434be8e3d7
